# Generated by Django 6.1 on 2026-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=100)),
                ('competencia', models.CharField(max_length=200)),
                ('ambiente', models.CharField(max_length=200)),
                ('aprendiz', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mi_curso',
            },
        ),
    ]
