# Generated by Django 6.1 on 2026-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_repaso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='micurso',
            name='cupos',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='micurso',
            name='duracion',
            field=models.CharField(default='40 horas', max_length=50),
        ),
    ]
