# Generated by Django 6.0.8 on 2026-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_capacitacion', models.CharField(max_length=255)),
                ('duracion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
            ],
        ),
    ]
