# Generated by Django 6.0.8 on 2026-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
