# Generated by Django 6.0.8 on 2026-09-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias_app', '0001_initial'),
        ('empresas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='categorias_app.categoria', verbose_name='Categoría'),
        ),
    ]
