# Generated by Django 6.0.8 on 2026-09-21 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_app', '0002_empresa_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del beneficio')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='beneficios',
            field=models.ManyToManyField(blank=True, to='empresas_app.beneficio', verbose_name='Beneficios ofrecidos'),
        ),
        migrations.CreateModel(
            name='PerfilExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
                ('link_linkedin', models.URLField(blank=True, null=True, verbose_name='Perfil de LinkedIn')),
                ('descripcion_larga', models.TextField(blank=True, null=True, verbose_name='Historia / Misión de la empresa')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_extra', to='empresas_app.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
