# Generated by Django 6.0.8 on 2026-09-04 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una categoría con este nombre exacto.'}, max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(blank=True, help_text='Texto utilizado normalmente en URLs', max_length=100, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Proporciona una descripción detallada de esta categoría.', verbose_name='Descripción')),
                ('tipo_categoria', models.CharField(choices=[('Laboral', 'Laboral'), ('Educativa', 'Educativa'), ('Comercial', 'Comercial'), ('Otra', 'Otra')], max_length=50, verbose_name='Tipo de categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado (Activa/Inactiva)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
