# Generated by Django 6.1.1 on 2026-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoEvacuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('capacidad', models.IntegerField(default=100)),
                ('estado', models.CharField(default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('tipo_emergencia', models.CharField(choices=[('Sismo', 'Sismo'), ('Incendio', 'Incendio'), ('Inundacion', 'Inundación'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Emergencia')),
                ('mensaje', models.TextField(verbose_name='Descripción de la Emergencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
