# Generated by Django 6.1.1 on 2026-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evacuacion_coderider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporteemergencia',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='reporteemergencia',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='reporteemergencia',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='reporteemergencia',
            name='tipo_emergencia',
        ),
        migrations.AddField(
            model_name='reporteemergencia',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios_emergencias/', verbose_name='Audio de la Emergencia'),
        ),
        migrations.AddField(
            model_name='reporteemergencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Adicional'),
        ),
        migrations.AddField(
            model_name='reporteemergencia',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos_emergencias/', verbose_name='Documento de la Emergencia'),
        ),
        migrations.AddField(
            model_name='reporteemergencia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_emergencias/', verbose_name='Foto de la Emergencia'),
        ),
        migrations.AddField(
            model_name='reporteemergencia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_emergencias/', verbose_name='Video de la Emergencia'),
        ),
    ]
