# Generated by Django 6.0.8 on 2026-09-04 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_completo', db_index=True, max_length=200)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('representante', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('numero_empleados', models.PositiveIntegerField(blank=True, db_comment='Cantidad total de empleados activos en la empresa', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'estado': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias_app.categoria', verbose_name='Categoría de la Empresa')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
