# Generated by Django 6.0.8 on 2026-09-04 14:11

import django.db.models.deletion
import django.db.models.functions.datetime
import ofertas_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id_candidato', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(error_messages={'blank': 'El nombre es un campo obligatorio.'}, max_length=150)),
                ('edad', models.PositiveSmallIntegerField(db_comment='Edad del usuario al registrarse', validators=[ofertas_app.models.validar_edad])),
                ('experiencia_meses', models.SmallIntegerField(default=0, verbose_name='Meses de experiencia')),
                ('expectativa_salarial', models.FloatField(blank=True, db_column='salario_esperado', null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_candidatos/')),
                ('portfolio_web', models.URLField(blank=True, help_text='Enlace a LinkedIn o portafolio personal')),
                ('ip_registro', models.GenericIPAddressField(blank=True, help_text='Dirección IPv4/IPv6 de registro', null=True)),
                ('habilidades_extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(db_tablespace='indice_slugs', max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('nivel_requerido', models.IntegerField(choices=[(1, 'Junior'), (2, 'Semi-Senior'), (3, 'Senior')], default=1)),
                ('vacantes', models.PositiveIntegerField(default=1)),
                ('vistas_totales', models.PositiveBigIntegerField(default=0, editable=False)),
                ('hora_publicacion', models.TimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', related_query_name='postulacion', to='ofertas_app.candidato')),
                ('oferta', models.ForeignKey(limit_choices_to={'activa': True}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos_inscritos', to='ofertas_app.ofertaempleo', to_field='slug')),
            ],
            options={
                'db_table': 'postulaciones_empleo',
            },
        ),
    ]
